apiVersion: batch/v1
kind: Job
metadata:
  name: ip-tool-collisions-job
  namespace: msci-home-assignment
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ip-tool
          image: tothdavid/msci-ha:latest
          args: ["--check-collision", "/ip-tool-data/ip-ranges/<file_name>"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IP_RANGES_DIR_PATH
              value: "/ip-tool-data/ip-ranges"
            - name: IP_RANGES_FILE_NAME
              value: "ip-ranges"
            - name: COLLISIONS_DIR_PATH
              value: "/ip-tool-data/collisions"
            - name: COLLISIONS_FILE_NAME
              value: "collisions"
            - name: LOGLEVEL
              value: "INFO"
          volumeMounts:
            - name: ip-tool-nfs-volume
              mountPath: /ip-tool-data
      volumes:
        - name: ip-tool-nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
  backoffLimit: 4
