apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: msci-home-assignment
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/nfs
    server: nfs-server.msci-home-assignment.svc.cluster.local
  storageClassName: nfs-storage
