apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: msci-home-assignment
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: minikube
    path: /data
    readOnly: no